- web/src/components/Form/FormFields/FieldWrapper.js
- web/src/components/Form/FormFields/InputField.js
- web/src/components/Form/FormFields/_FieldWrapper.scss
- web/src/components/Form/FormFields/_FormFields.scss
- web/src/config/en.js
- web/src/containers/Withdraw/form.js
- web/src/containers/Withdraw/formUtils.js
- web/src/index.css
destination tag field changes for xrp withdrawal
> changes for destination tag field in withdraw form

- web/package.json
- web/src/components/AppBar/_AppBar.scss
- web/src/components/AppBar/index.js
- web/src/components/AppFooter/_AppFooter.scss
- web/src/components/AppFooter/index.js
- web/src/config/constants.js
- web/src/config/en.js
- web/src/config/ko.js
- web/src/containers/TradeTabs/index.js
- web/src/index.css
> Hollaex-Kit@1.20.15

- mail/templates/helpers/common.js
Removed extra DOMAIN variable declaration
> Fixed bug 

- db/migrations/20200303044931-add-tech-role.js
- db/models/user.js
- db/pubsub.js
- db/redis.js
- db/seeders/20190825120350-add-status.js
Default values (`LANGUAGE`, `THEME`, `NEW_USER_IS_ACTIVATED`) for the User model are being read dynamically instead of from env.
- `NEW_USER_IS_ACTIVE` is being stored as a boolean initially now.
- The `if (logger)` check in redis files are there because core was throwing errors about not being able to find the loggers after requiring subscriber in `constants.js`.
> applying db changes made in core

- mail/strings/fa.js
- web/src/config/fa.js
> fa is added for mail and web

- db/seeders/20190825120350-add-status.js
- plugins/index.js
- plugins/kyc/helpers.js
- plugins/kyc/s3.js
- plugins/sms/sns.js
- add description, links, title in constants
- move plugins configurations from constants to secrets
> Admin settings

- plugins/index.js
- plugins/vault/helpers.js
- plugins/vault/index.js
- plugins/xht_fee/index.js
- `GET /plugins/vault/disconnect` sets vault values in constants to empty values
> Vault disconnect

- mail/templates/helpers/common.js
> rtl for email is added 2

- web/package-lock.json
- web/src/components/Chat/ChatMessage.js
- web/src/components/Chat/_Chat.scss
> chat issue is solved

- db/seeders/20190825120350-add-status.js
- plugins/vault/crons/checkWithdrawals.js
- plugins/vault/crons/lockWithdrawals.js
- plugins/vault/crons/processWithdrawals.js
- plugins/vault/helpers.js
- plugins/vault/index.js
- plugins/vault/package.json
- add cron job for batch withdrawal
- add cron_task_interval to constants
> Batch withdraw

- plugins/constants.js
- plugins/helpers/common.js
- plugins/index.js
- plugins/vault/crons/checkWithdrawals.js
- plugins/vault/crons/lockWithdrawals.js
- plugins/vault/crons/processWithdrawals.js
- plugins/vault/helpers.js
- fixed import directories for batch withdrawal cron job files
- fixed batch withdrawal cron job sleep function
- hardcoded available plugins array to plugins/constants.js
- cleaned up plugins/index.js
> Plugins fixes

- plugins/vault/crons/processWithdrawals.js
check if bch/btc withdrawals are being made to the same address in one batch
> add same address check for btc and bch withdrawals in processwithdrawal

- plugins/vault/crons/checkWithdrawals.js
- plugins/vault/crons/lockWithdrawals.js
- plugins/vault/crons/processWithdrawals.js
- plugins/vault/helpers.js
- make every cron job function into a promise
- checkAddress fix
> checkAddress fix for vault

- plugins/vault/crons/checkWithdrawals.js
- plugins/vault/crons/lockWithdrawals.js
- plugins/vault/crons/processWithdrawals.js
- plugins/vault/package.json
- amounts being sent are set as amount - fee
- better logs
- mathjs added to vault package.json
> batch withdrawals amount being sent = amount - fee

- plugins/index.js
app uses cors library before making endpoint /plugins
> cors plugins fix

- web/package-lock.json
- web/src/_common.scss
- web/src/components/Chat/ChatMessage.js
- web/src/index.css
> chat contents no longer goes down

- web/package-lock.json
- web/src/_common.scss
- web/src/components/AppBar/HamburgerMenu.js
- web/src/components/AppBar/index.js
- web/src/config/lang/en.js
- web/src/containers/Signup/SignupForm.js
- web/src/containers/Signup/index.js
- web/src/index.css
- web/src/index.scss
burger menu and signup referral code
> burger menu and signup referral code

- web/src/components/AppBar/index.js
- web/src/containers/Signup/SignupForm.js
- web/src/containers/Signup/index.js
- web/src/index.css
- web/src/index.scss
> burger menu is removed

- web/src/components/AppBar/SearchBox.js
- web/src/components/Form/FormFields/CheckField.js
- web/src/components/NotificationsList/index.js
- web/src/components/Wallet/AssetsBlockForm.js
- web/src/components/index.js
- web/src/containers/Admin/Plugins/Announcement.js
- web/src/containers/Wallet/AssetsBlock.js
- web/src/containers/Wallet/MainWallet.js
- web/src/containers/Wallet/_Wallet.scss
- web/src/index.css
**Functionalities added to Wallet Page:**
- Trade column which brings the user to the trade page (hidden on mobile devices)
- Search improvement header ( including search-bar and hide-zero-assets )
- Results are sorted based on the price balance
- Footer is removed ( contact-us dialog for XHT BASE_CURRENCY moved to the header)
> Multiple coins

- plugins/helpers/common.js
maskSecrets not manipulating original data
> maskSecrets fix

- server/api/controllers/notification.js
- server/constants.js
- server/ws/sub.js
- Using pubsub to publish completed deposit data to websocket
- Websocket sends deposit to user
> deposit websocket notification on completed deposit

- server/api/controllers/order.js
- server/api/swagger/swagger.yaml
- add type query to get orders
> add type to order query

- server/constants.js
- Helper function changes were made to tools library
https://github.com/bitholla/hollaex-tools-lib/pull/4
> hmac token redis key added

- web/src/actions/walletActions.js
- web/src/components/Wallet/index.js
- web/src/containers/Wallet/AssetsBlock.js
- web/src/containers/Wallet/MainWallet.js
- web/src/index.css
- web/src/utils/currency.js
> Price conversion

- server/init.js
exporting node library from init
> export node lib from init.js

- server/api/controllers/user.js
- server/api/swagger/swagger.yaml
`PUT /user/settings` fix
- Omit password and operator fields when returning
- Fixed bug that didn't update settings field
> get user fix, settings update fix

- server/package.json
- server/plugins.js
use cors library for plugins express app
> add cors to plugins

- server/api/controllers/order.js
- bug fix to pass stop price to network or order creation
> stop order fix

- server/api/swagger/swagger.yaml
- server/app.js
- server/constants.js
- server/db/seeders/20190825120350-add-status.js
- server/package.json
- server/tools/dbs/checkConfig.js
- server/tools/dbs/setConfig.js
- Explorer added
- Sender and audit email default values removed
> remove sender, admin email default values

- server/api/controllers/tier.js
- server/constants.js
- server/db/seeders/20201014074533-add-tiers.js
- server/init.js
Requires Tools library PR to be merged:
https://github.com/bitholla/hollaex-tools-lib/pull/16
> remove default fee

- server/api/controllers/deposit.js
- server/api/controllers/withdrawal.js
- server/api/swagger/swagger.yaml
- add `transaciton_id`, `address` to `GET admin/deposits`, `GET admin/withdrawals`
- add `status`, `processing`, `waiting`, `rejected`, `dismissed`, `transaction_id`, `address` to `GET /user/deposits`, `GET user/withdrawals`
> filter fix for get user/admin deposits/withdrawals

- server/api/controllers/admin.js
- server/api/swagger/swagger.yaml
- server/db/migrations/20210416020745-add-user-discount.js
- server/db/models/user.js
**Requires [tools library PR](https://github.com/bitholla/hollaex-tools-lib/pull/21) to be merged**
Added migration for `user.discount` and `discount` in model
- default value: 0
- type: double
- Is a percentage
Add endpoint `PUT /admin/user/discount`
- Requires `user_id` in query and `discount` in body
- Discount must be between 0 ~ 100
Discount is applied during order creation
- Calculation: `discounted fee` = (`tier maker||taker fee`) - (`tier maker||taker fee` * (`user.discount` / `100`))
- If `discounted fee` is less than the minimum fee determined by `collateral_level`, the fee is set to the `minimum fee`
> Add discount to user model

- server/db/migrations/20210504082609-add-plugin-public_meta.js
- server/db/models/plugin.js
- server/plugins.js
- Add `public_meta` to plugins model
- Migration file for `public_meta`
- `GET /plugins` includes `public_meta`
- `PUT, POST /plugins` updates `public_meta`
- Endpoint `PUT /plugins/public-meta` updates plugin `public_meta`
- `PUT /plugins/public-meta`, `PUT /plugins/meta` adds new fields included
> add public meta to plugin model

- server/plugins.js
Added more default libraries to plugins
> additional default plugin libraries included

- server/package.json
Tools Library PR: 
https://github.com/bitholla/hollaex-tools-lib/pull/36
> tools library => 2.4

- server/api/controllers/admin.js
- server/api/swagger/swagger.yaml
- server/package.json
**TOOLS LIB BRANCH UPDATE [2.14 => 2.15 PR](https://github.com/bitholla/hollaex-tools-lib/pull/70)**
`PUT /admin/user` added
- Allows admin to update user's
- `full_name`
- `nationality`
- `dob`
- `gender`
- `phone_number`
- `address`
> Admin user endpoint

- server/package.json
- server/utils/toolsLib/tools/wallet.js
- Install `multicoin-address-validator v0.4.4`
- Check withdrawal address during withdrawal request check
- Throw an error if `network` is passed for a coin that has `network === null`
> Request withdrawal improvement

- web/src/actions/orderAction.js
- web/src/config/lang/ar.js
- web/src/config/lang/en.js
- web/src/containers/Trade/utils.js
(cherry picked from commit bab2359)
> symbol-specific active orders

- server/mail/templates/accountUpgrade.js
- server/mail/templates/accountVerify.js
- server/mail/templates/alert.js
- server/mail/templates/bankVerified.js
- server/mail/templates/changePassword.js
- server/mail/templates/contactForm.js
- server/mail/templates/deposit.js
- server/mail/templates/depositCancel.js
- server/mail/templates/discountUpdate.js
- server/mail/templates/invalidAddress.js
- server/mail/templates/invitedOperator.js
- server/mail/templates/login.js
- server/mail/templates/passwordChanged.js
- server/mail/templates/resetPassword.js
- server/mail/templates/signup.js
- server/mail/templates/suspiciousDeposit.js
- server/mail/templates/userDeactivated.js
- server/mail/templates/userVerification.js
- server/mail/templates/userVerificationReject.js
- server/mail/templates/welcome.js
- server/mail/templates/withdrawal.js
- server/mail/templates/withdrawalRequest.js
update dynamic string email for case missing key
> update dynamic string email for case missing key

- server/api/controllers/admin.js
- server/api/swagger/swagger.yaml
- server/mail/index.js
- server/mail/utils.js
init feat sent email test config
> init feat sent email test config

- server/db/migrations/20220310103359-add-security-email-template.js
update file migration for confirm email
> update file migration for confirm email

- server/api/controllers/admin.js
- server/api/swagger/swagger.yaml
Update endpoint for task dynamic email
> Update endpoint for task dynamic email

- server/mail/strings/index.js
- server/mail/templates/index.js
> fix issue dynamic email

- server/api/controllers/broker.js
- server/utils/hollaex-tools-lib/tools/broker.js
- account and formula fields are removed  for non users and users that are not admin
- expiry date added for dynamic and manual brokers
> Advanced broker update

- server/utils/hollaex-tools-lib/tools/broker.js
This reverts commit e51eb1e4b41341c97725ee2613f826c722c71e47.
> Revert "revert update pair service"

- web/src/utils/currency.js
changing fees percentage accuracy to three decimal places
> Fix fees percentage format on Summary

- web/src/components/Notification/constants.js
- web/src/containers/Deposit/utils.js
- web/src/containers/Summary/MobileSummary.js
- web/src/containers/Summary/index.js
- web/src/containers/Trade/components/OrderEntryForm.js
- web/src/containers/Trade/components/RiskyOrder.js
- web/src/containers/TransactionsHistory/utils.js
- web/src/containers/UserSettings/SetOrderPortfolio.js
- web/src/containers/Verification/MobileVerification.js
- web/src/containers/Wallet/components/CurrencySlider.js
- web/src/containers/Withdraw/Fiat/FormUtils.js
- web/src/containers/Withdraw/formUtils.js
- web/src/utils/countries.js
> Revert "react localization update"

- web/src/components/AppBar/PairTabs.js
- web/src/components/AppBar/index.js
- web/src/components/AppFooter/_AppFooter.scss
- web/src/config/lang/en.json
- web/src/config/lang/id.json
- web/src/config/menu.js
- web/src/containers/App/App.js
- web/src/containers/Home/index.js
- web/src/containers/Summary/components/Markets.js
- web/src/index.scss
- web/src/routes.js
-Add scroll to long pop up for view fees Fixed,
-Add animated slide effect for top nav Fixed
-Improve sidebar Fixed,
-Select level is gray, change to main active color white(dark theme) Fixed,
-Improve logo positioning Fixed,
-Audio cue, drop Play Fixed,
-Improve market list URL Fixed,
> Fixes 23-08

- test/Cypress/cypress/integration/Gherkin/pre/pre.js
The code is updated with regard to the button name change, from Play Audio cue to  Audio cues
> precondition of testing fix, Audio cues

- web/src/components/Form/FormFields/PinInput.js
- web/src/components/Form/FormFields/_FormFields.scss
- web/src/components/Form/FormFields/_PinInput.scss
- web/src/components/Form/factoryFields.js
- web/src/components/OtpForm/_OtpForm.scss
- web/src/components/OtpForm/index.js
- web/src/config/lang/en.json
PIN input is implemented to use in the login OTP form.
> pin input for otp

- web/src/index.css
> index.css added into PR

- web/src/containers/Wallet/AssetsBlock.js
- web/src/utils/currency.js
> Wallet formats update

- test/Cypress/package.json
For performance analysis, some packages are added.
> Package.json is updated

- test/Cypress/cypress/cucumber-json/accountLevel.cucumber.json
- test/Cypress/cypress/cucumber-json/chatbox.cucumber.json
- test/Cypress/cypress/cucumber-json/login.cucumber.json
- test/Cypress/cypress/cucumber-json/loginPerf.cucumber.json
- test/Cypress/cypress/cucumber-json/login_perf.cucumber.json
- test/Cypress/cypress/cucumber-json/logout.cucumber.json
- test/Cypress/cypress/cucumber-json/performance.cucumber.json
- test/Cypress/cypress/cucumber-json/pre.cucumber.json
- test/Cypress/cypress/cucumber-json/promotion.cucumber.json
- test/Cypress/cypress/cucumber-json/refferal.cucumber.json
- test/Cypress/cypress/cucumber-json/resendVerificationEmail.cucumber.json
- test/Cypress/cypress/cucumber-json/resetPassword.cucumber.json
- test/Cypress/cypress/cucumber-json/roles.cucumber.json
- test/Cypress/cypress/cucumber-json/security.cucumber.json
- test/Cypress/cypress/cucumber-json/setting.cucumber.json
- test/Cypress/cypress/cucumber-json/signup.cucumber.json
- test/Cypress/cypress/cucumber-json/signupWithEmail.cucumber.json
- test/Cypress/cypress/cucumber-json/trade.cucumber.json
- test/Cypress/cypress/cucumber-json/transactionFlow.cucumber.json
- test/Cypress/cypress/cucumber-json/wallet.cucumber.json
- test/Cypress/cypress/integration/Gherkin/loginPerf.feature
- test/Cypress/cypress/integration/Gherkin/loginPerf/loginPerf.js
The logging performance is added
> login performance is added

- web/src/components/AdminForm/hoc.js
- web/src/containers/Admin/Verification/index.js
- web/src/containers/DigitalAssets/index.js
Fixed the quick trade link showing issue.
> Fixed the button overlap issue.

- web/src/containers/Admin/Billing/Billing.scss
- web/src/containers/Admin/Billing/index.js
- web/src/containers/Admin/Billing/planStructure.js
- web/src/utils/request.js
Fixed the `unhandling rejection` error on the billing page.
> Simplified the pop-up UI in the billing page.

- test/Cypress/cypress/integration/Gherkin/createUserByAdmin.feature
- test/Cypress/cypress/integration/Gherkin/createUserByAdmin/createUserByAdmin.js
Create by admin feature test is done.
> create by admin feature test

- test/Cypress/cypress/integration/Gherkin/adminCreateWallet.feature
- test/Cypress/cypress/integration/Gherkin/adminCreateWallet/adminCreateWallet.js
- test/Cypress/cypress/integration/Gherkin/createUserByAdmin.feature
- test/Cypress/cypress/integration/Gherkin/createUserByAdmin/createUserByAdmin.js
Admin can create wallets for the users
> Admin create wallets for the users

- web/src/containers/Admin/General/EditToken.js
- web/src/containers/Admin/General/GenerateApiKeys.js
- web/src/containers/Admin/General/index.css
Removed the dropdown on the Generate API key pop-up flow.
> Implemented the edit flow for the  white listed IPs.

- web/src/components/QuickTrade/index.js
- web/src/containers/UserSettings/AudioForm.js
- web/src/containers/UserSettings/NotificationForm.js
- web/src/containers/UserSettings/RiskForm.js
- web/src/containers/UserSettings/index.js
> Fixed button key language issue on the settings in the kit.

- web/src/components/Notification/NewOrder.js
- web/src/components/QuickTrade/index.js
- web/src/config/index.js
- web/src/config/lang/en.json
- web/src/containers/App/App.js
- web/src/containers/QuickTrade/_QuickTrade.scss
- web/src/containers/QuickTrade/components/ReviewOrder.js
- web/src/containers/QuickTrade/components/RiskyTrade.js
- web/src/index.css
https://www.notion.so/hollaex/Disclaimer-for-risky-coins-3b41728cd54c40c595ecc4aedc1ed588
> Risky Trade Disclaimer

- test/Cypress/cypress/integration/Gherkin/roles.feature
- test/Cypress/cypress/integration/Gherkin/roles/roles.js
Roles' test is updated; the test is bulky and needs to be broken down.
> Roles are updated

- web/src/components/AppBar/MarketSelector.js
- web/src/components/PriceChange/index.js
- web/src/index.css
- Fix search of dropdown
- Sorting order Pro items above quick trade items
- Pinned markets show on top
- Fix Tab filters as well
> Issues of Market Select Dropdown

- test/Cypress/cypress/integration/Gherkin/tradePerf.feature
- test/Cypress/cypress/integration/Gherkin/tradePerf/tradePerf.js
This is a test to evaluate the trading performance from the end user's perspective. The test criteria are based on specific time limits, but it's important to note that the speed may be influenced by exchange traffic, net speed, and the specifications of your runner and machine.
> trading performance test is added

- web/src/components/QuickTrade/index.js
Fix issue of keyboard opening automatically in Mobile
> Fix mobile keyboard opening

- test/Cypress/cypress/integration/Gherkin/userDeleteAccount.feature
- test/Cypress/cypress/integration/Gherkin/userDeleteAccount/userDeleteAcount.js
> user delete account test is added

- server/api/controllers/user.js
> notify-admin-on-bank-add

- server/constants.js
- server/init.js
- server/utils/hollaex-tools-lib/tools/common.js
- web/src/containers/Admin/Fiat/FiatFees.js
- web/src/containers/Admin/Fiat/index.js
`Fiat Fees` tab updaded to `Fiat Fees & Customization`
new fields on the table added, If we do not have a custom value for them, we show their default value.
> Fiat customization

- server/README.md
> docs: update server/README.md
